import { describe, expect, it } from 'vitest'
import {
  parseT212Money,
  parseT212StatementText,
  pairT212Executions,
  rebuildT212History,
  t212ExecutionId,
} from './t212-statement'
import type { T212Execution } from './t212-statement'

function exec(partial: Omit<T212Execution, 'id'>): T212Execution {
  return { ...partial, id: t212ExecutionId(partial) }
}

const samplePdfText = `
Activity statement
Generated by Trading 212 Markets Ltd.
CFD account - executed trades
EXECUTION TIME INSTRUMENT ORDER ID ORDER TYPE DIRECTION EXECUTION VENUE POSITION SIZE AVERAGE PRICE EXECUTION PRICE VALUE SPREAD FX RATE FX FEE RESULT
2026-08-04
09:21:50 GER40 55200123245 Market Buy OTC 0.00381605 - €26,205.1 €100 - - - - - - -
2026-08-06
14:00:00 GER40 55200129999 Market Sell OTC 0.00381605 - €26,400.0 €100.7 - - - €0.74 - - €0.74
Invest account - executed trades
No data available
Glossary
`

describe('parseT212Money', () => {
  it('parses euro thousands and decimals', () => {
    expect(parseT212Money('€26,205.1')).toBe(26205.1)
    expect(parseT212Money('€-0.01')).toBeCloseTo(-0.01)
    expect(parseT212Money('-')).toBeUndefined()
  })
})

describe('parseT212StatementText', () => {
  it('pairs CFD buy then sell into a closed trade', () => {
    const result = parseT212StatementText(samplePdfText)
    expect(result.executions).toHaveLength(2)
    expect(result.closedTrades).toHaveLength(1)
    expect(result.openExecutions).toHaveLength(0)
    expect(result.closedTrades[0].base).toBe('GER40')
    expect(result.closedTrades[0].venue).toBe('t212')
    expect(result.closedTrades[0].pnlUsdc).toBeCloseTo(0.74, 2)
  })

  it('parses pdfjs one-line CFD execution blob', () => {
    const blob = `CFD account - executed trades EXECUTION TIME INSTRUMENT ORDER ID ORDER TYPE DIRECTION EXECUTION VENUE POSITION SIZE AVERAGE PRICE EXECUTION PRICE VALUE SPREAD FX RATE FX FEE RESULT DIVIDEND ADJUSTMENTS OVERNIGHT INTEREST TOTAL RESULT 2026-08-04 09:21:50 GER40 55200123245 Market Buy OTC 0.00381605 - €26,205.1 €100 - - - - - - - CUSTOMER ID`
    const result = parseT212StatementText(blob)
    expect(result.executions).toHaveLength(1)
    expect(result.executions[0].instrument).toBe('GER40')
    expect(result.executions[0].price).toBe(26205.1)
    expect(result.closedTrades).toHaveLength(0)
    expect(result.openExecutions).toHaveLength(1)
  })
})

describe('pairT212Executions short', () => {
  it('closes short sell then buy with computed pnl', () => {
    const execs: T212Execution[] = [
      exec({
        time: Date.parse('2026-08-01T10:00:00Z'),
        instrument: 'META',
        orderId: '1',
        direction: 'Sell',
        size: 1,
        price: 600,
        source: 'cfd',
      }),
      exec({
        time: Date.parse('2026-08-02T10:00:00Z'),
        instrument: 'META',
        orderId: '2',
        direction: 'Buy',
        size: 1,
        price: 580,
        source: 'cfd',
      }),
    ]
    const { closedTrades, openExecutions } = pairT212Executions(execs)
    expect(openExecutions).toHaveLength(0)
    expect(closedTrades).toHaveLength(1)
    expect(closedTrades[0].pnlUsdc).toBeCloseTo(20)
  })
})

describe('rebuildT212History across statements', () => {
  it('closes an open from PDF1 when PDF2 brings the sell', () => {
    const openOnly = parseT212StatementText(`
CFD account - executed trades
2026-08-04 09:21:50 GER40 55200123245 Market Buy OTC 0.00381605 - €26,205.1 €100 - - - - - - -
`)
    expect(openOnly.openExecutions).toHaveLength(1)
    expect(openOnly.closedTrades).toHaveLength(0)

    const laterSell = exec({
      time: Date.parse('2026-08-06T14:00:00Z'),
      instrument: 'GER40',
      orderId: '55200129999',
      direction: 'Sell',
      size: 0.00381605,
      price: 26400,
      result: 0.74,
      source: 'cfd',
    })
    const rebuilt = rebuildT212History([...openOnly.executions, laterSell])
    expect(rebuilt.closedTrades).toHaveLength(1)
    expect(rebuilt.openExecutions).toHaveLength(0)
    expect(rebuilt.closedTrades[0].pnlUsdc).toBeCloseTo(0.74, 2)
  })
})
