import { getTradingSessionStatus } from '../trading-session'
import type { ClosedTrade } from './types'

export type T212ExecDirection = 'Buy' | 'Sell'
export type T212ExecSource = 'cfd' | 'invest'

/** Uma linha de «executed trades» no Activity Statement. */
export type T212Execution = {
  /** Id estável para merge entre PDFs. */
  id: string
  time: number
  instrument: string
  orderId: string
  direction: T212ExecDirection
  size: number
  price: number
  value?: number
  /** RESULT / TOTAL RESULT (EUR tipicamente) na linha de fecho. */
  result?: number
  source: T212ExecSource
}

export type T212StatementMeta = {
  periodFrom?: string
  periodTo?: string
  generatedAt?: string
}

export type T212StatementParseResult = {
  meta: T212StatementMeta
  executions: T212Execution[]
  closedTrades: ClosedTrade[]
  openExecutions: T212Execution[]
}

export function t212ExecutionId(e: Omit<T212Execution, 'id'>): string {
  return `${e.source}:${e.orderId}:${e.time}:${e.direction}:${e.size}:${e.price}`
}

/** Parse valores tipo €26,205.1 / €-0.01 / 26.205,1 */
export function parseT212Money(raw: string): number | undefined {
  const cleaned = raw.replace(/[€$£\s]/g, '').trim()
  if (!cleaned || cleaned === '-' || cleaned === '—') return undefined
  if (/^-?\d{1,3}(,\d{3})+(\.\d+)?$/.test(cleaned)) {
    const n = Number(cleaned.replace(/,/g, ''))
    return Number.isFinite(n) ? n : undefined
  }
  if (/^-?\d{1,3}(\.\d{3})*(,\d+)?$/.test(cleaned) || /^-?\d+,\d+$/.test(cleaned)) {
    const n = Number(cleaned.replace(/\./g, '').replace(',', '.'))
    return Number.isFinite(n) ? n : undefined
  }
  const n = Number(cleaned.replace(/,/g, ''))
  return Number.isFinite(n) ? n : undefined
}

/** CFD: … ORDER TYPE DIRECTION VENUE SIZE AVG PRICE VALUE … */
const CFD_EXEC_RE =
  /(?<date>\d{4}-\d{2}-\d{2})\s+(?<time>\d{2}:\d{2}:\d{2})\s+(?<instrument>[A-Za-z0-9._/-]+)\s+(?<orderId>\d+)\s+\S+\s+(?<direction>Buy|Sell)\b(?:\s+(?![\d.])\S+)?\s+(?<size>[\d.,]+)\s+(?<avg>\S+)\s+(?<price>\S+)\s+(?<value>\S+)/gi

/** Invest: … INSTRUMENT ISIN ORDER ID DIRECTION QTY PRICE VALUE … */
const INVEST_EXEC_RE =
  /(?<date>\d{4}-\d{2}-\d{2})\s+(?<time>\d{2}:\d{2}:\d{2})\s+(?<instrument>[A-Za-z0-9._/-]+)\s+(?<isin>[A-Z]{2}[A-Z0-9]{9,12})\s+(?<orderId>\d+)\s+(?<direction>Buy|Sell)\b\s+(?<size>[\d.,]+)\s+(?<price>\S+)\s+(?<value>\S+)/gi

/**
 * Extrai execuções CFD + Invest do Activity Statement T212.
 * Fecha round-trips Buy↔Sell por instrumento (FIFO) — histórico cresce com mais PDFs.
 */
export function parseT212StatementText(text: string): T212StatementParseResult {
  const normalized = text.replace(/\r\n/g, '\n')
  const meta = parseStatementMeta(normalized)
  const cfd = extractExecutions(normalized, 'CFD account - executed trades', 'cfd', CFD_EXEC_RE)
  const invest = extractExecutions(normalized, 'Invest account - executed trades', 'invest', INVEST_EXEC_RE)
  const executions = dedupeExecutions([...cfd, ...invest]).sort((a, b) => a.time - b.time || a.id.localeCompare(b.id))
  const { closedTrades, openExecutions } = pairT212Executions(executions)
  return { meta, executions, closedTrades, openExecutions }
}

/** Junta ledgers de vários statements e reconstrói fechados + abertos. */
export function rebuildT212History(executions: T212Execution[]): {
  executions: T212Execution[]
  closedTrades: ClosedTrade[]
  openExecutions: T212Execution[]
} {
  const merged = dedupeExecutions(executions).sort((a, b) => a.time - b.time || a.id.localeCompare(b.id))
  const { closedTrades, openExecutions } = pairT212Executions(merged)
  return { executions: merged, closedTrades, openExecutions }
}

export function dedupeExecutions(executions: T212Execution[]): T212Execution[] {
  const map = new Map<string, T212Execution>()
  for (const e of executions) {
    const id = e.id || t212ExecutionId(e)
    const prev = map.get(id)
    if (!prev) {
      map.set(id, { ...e, id })
      continue
    }
    // Preferir linha com RESULT preenchido
    if (prev.result === undefined && e.result !== undefined) map.set(id, { ...e, id })
  }
  return [...map.values()]
}

function parseStatementMeta(text: string): T212StatementMeta {
  const meta: T212StatementMeta = {}
  const period = text.match(/covering from\s+(\d{2}\.\d{2}\.\d{4}\s+\d{2}:\d{2}\s*\([^)]+\))\s+to\s+(\d{2}\.\d{2}\.\d{4}\s+\d{2}:\d{2}\s*\([^)]+\))/i)
  if (period) {
    meta.periodFrom = period[1]
    meta.periodTo = period[2]
  }
  const gen = text.match(/Generated by Trading 212[^\n]*on\s+(\d{1,2}\s+\w+\s+\d{4})/i)
  if (gen) meta.generatedAt = gen[1]
  return meta
}

function extractExecutions(
  text: string,
  header: string,
  source: T212ExecSource,
  pattern: RegExp,
): T212Execution[] {
  const start = text.indexOf(header)
  if (start < 0) return []
  let after = text.slice(start + header.length)
  const endMatch = after.search(/\n\s*(Invest account|CFD account|Glossary|Disclosures)\b/i)
  if (endMatch >= 0) after = after.slice(0, endMatch)
  const endInline = after.search(/\s{1,3}(Invest account|CFD account - open|Glossary|Disclosures)\b/i)
  if (endInline >= 0 && (endMatch < 0 || endInline < endMatch)) after = after.slice(0, endInline)
  if (/No data available/i.test(after.slice(0, 500))) return []

  const compact = after.replace(/\t/g, ' ').replace(/\s+/g, ' ')
  const out: T212Execution[] = []
  const re = new RegExp(pattern.source, 'gi')
  const matches = [...compact.matchAll(re)]
  for (let i = 0; i < matches.length; i += 1) {
    const m = matches[i]
    const end = i + 1 < matches.length ? matches[i + 1].index! : compact.length
    const rest = compact.slice(m.index! + m[0].length, end).trim()
    if (m.groups) m.groups.rest = rest
    const row = parseExecutionMatch(m, source)
    if (row) out.push(row)
  }
  return out
}

function parseExecutionMatch(m: RegExpExecArray, source: T212ExecSource): T212Execution | undefined {
  const g = m.groups
  if (!g) return undefined
  const { date, time, instrument, orderId, direction, size, avg, price, value, rest } = g
  const ts = Date.parse(`${date}T${time}Z`)
  if (!Number.isFinite(ts)) return undefined
  const sizeN = parseT212Money(size)
  const priceN = parseT212Money(price) ?? (avg ? parseT212Money(avg) : undefined)
  if (sizeN === undefined || sizeN <= 0 || priceN === undefined || priceN <= 0) return undefined
  const base = {
    time: ts,
    instrument: instrument.toUpperCase(),
    orderId,
    direction: (direction === 'Sell' ? 'Sell' : 'Buy') as T212ExecDirection,
    size: sizeN,
    price: priceN,
    value: parseT212Money(value),
    result: pickResultFromRest(rest ?? ''),
    source,
  }
  return { ...base, id: t212ExecutionId(base) }
}

function pickResultFromRest(rest: string): number | undefined {
  const tokens = rest.split(/\s+/).filter(Boolean)
  const moneys: number[] = []
  for (const token of tokens) {
    if (token === '-' || token === '—') continue
    // Ignorar % e códigos tipo 4.43%
    if (/%$/.test(token)) continue
    const n = parseT212Money(token)
    if (n !== undefined) moneys.push(n)
  }
  if (moneys.length === 0) return undefined
  return moneys[moneys.length - 1]
}

type Lot = {
  time: number
  price: number
  size: number
  orderId: string
  direction: T212ExecDirection
  source: T212ExecSource
}

export function pairT212Executions(executions: T212Execution[]): {
  closedTrades: ClosedTrade[]
  openExecutions: T212Execution[]
} {
  const lotsByKey = new Map<string, Lot[]>()
  const closed: ClosedTrade[] = []

  for (const exec of executions) {
    const key = `${exec.source}:${exec.instrument}`
    const lots = lotsByKey.get(key) ?? []
    const canClose = lots.length > 0 && lots[0].direction !== exec.direction

    if (!canClose) {
      lots.push({
        time: exec.time,
        price: exec.price,
        size: exec.size,
        orderId: exec.orderId,
        direction: exec.direction,
        source: exec.source,
      })
      lotsByKey.set(key, lots)
      continue
    }

    let remaining = exec.size
    // Weighted average entry across partial fills in this closing wave
    let entryTimeSum = 0
    let entryPriceSum = 0
    let entryOrderId = lots[0].orderId
    let entryDir = lots[0].direction
    let allocatedPnl = 0
    let allocatedQty = 0

    while (remaining > 1e-12 && lots.length > 0 && lots[0].direction !== exec.direction) {
      const lot = lots[0]
      const matched = Math.min(remaining, lot.size)
      const ratio = exec.size > 0 ? matched / exec.size : 0
      entryTimeSum += lot.time * matched
      entryPriceSum += lot.price * matched
      entryOrderId = lot.orderId
      entryDir = lot.direction
      if (exec.result !== undefined) allocatedPnl += exec.result * ratio
      else {
        const long = entryDir === 'Buy'
        allocatedPnl += long
          ? (exec.price - lot.price) * matched
          : (lot.price - exec.price) * matched
      }
      allocatedQty += matched
      remaining -= matched
      lot.size -= matched
      if (lot.size <= 1e-12) lots.shift()
    }

    if (allocatedQty > 1e-12) {
      pushClosed(closed, {
        instrument: exec.instrument,
        entryTime: entryTimeSum / allocatedQty,
        exitTime: exec.time,
        entryPrice: entryPriceSum / allocatedQty,
        exitPrice: exec.price,
        quantity: allocatedQty,
        pnl: allocatedPnl,
        entryOrderId,
        exitOrderId: exec.orderId,
        source: exec.source,
      })
    }

    if (remaining > 1e-12) {
      lots.push({
        time: exec.time,
        price: exec.price,
        size: remaining,
        orderId: exec.orderId,
        direction: exec.direction,
        source: exec.source,
      })
    }
    lotsByKey.set(key, lots)
  }

  const openExecutions: T212Execution[] = []
  for (const [key, lots] of lotsByKey) {
    const instrument = key.split(':').slice(1).join(':')
    for (const lot of lots) {
      const base = {
        time: lot.time,
        instrument,
        orderId: lot.orderId,
        direction: lot.direction,
        size: lot.size,
        price: lot.price,
        source: lot.source,
      }
      openExecutions.push({ ...base, id: t212ExecutionId(base) })
    }
  }

  return { closedTrades: closed, openExecutions }
}

function pushClosed(
  closed: ClosedTrade[],
  row: {
    instrument: string
    entryTime: number
    exitTime: number
    entryPrice: number
    exitPrice: number
    quantity: number
    pnl: number
    entryOrderId: string
    exitOrderId: string
    source: T212ExecSource
  },
) {
  const entrySession = getTradingSessionStatus(new Date(row.entryTime), { market: 'cfd' })
  const exitSession = getTradingSessionStatus(new Date(row.exitTime), { market: 'cfd' })
  const cost = Math.abs(row.entryPrice * row.quantity)
  const pnlPct = cost > 0 ? (row.pnl / cost) * 100 : 0
  closed.push({
    id: `t212-${row.source}-${row.instrument}-${row.entryOrderId}-${row.exitOrderId}-${Math.round(row.entryTime)}-${row.exitTime}`,
    symbol: row.instrument,
    base: row.instrument,
    entryTime: Math.round(row.entryTime),
    exitTime: row.exitTime,
    entryPrice: row.entryPrice,
    exitPrice: row.exitPrice,
    quantity: row.quantity,
    pnlUsdc: row.pnl,
    pnlPct,
    feesUsdc: 0,
    entrySession: entrySession.window,
    entrySessionBadge: entrySession.badge,
    exitSession: exitSession.window,
    exitSessionBadge: exitSession.badge,
    durationMs: row.exitTime - Math.round(row.entryTime),
    venue: 't212',
  })
}
